apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: my-k8s-learning-com-tls
spec:
    secretName: k8s-learning-com
    issuerRef: 
        name: letencrypt-prod
        kind: ClusterIssuer
    commonName: k8s-learning.com
    dnsNames:
        -   k8s-learning.com
        -   www.k8s-learning.com
    acme:
        config:
            -   http01:
                    ingressClass: nginx
                domains:
                    -   k8s-learning.com
                    -   www.k8s-learning.com